server:
  port: 8082


spring:
  datasource:
    continue-on-error: true
    initialization-mode: always
    initialize: true
    schema: classpath:/schema.sql
    url: jdbc:postgresql://localhost:5432/practice
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: create
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: HOTEL-SERVICE
  config:
    import: optional:configserver:http://localhost:8085



okta:
  oauth2:
    issuer: https://dev-04940289.okta.com/oauth2/default
    audience: api://default



  kafka:
    consumer:
      group-id: tpd-loggers
      auto-offset-reset: earliest
    # change this property if you are using your own
    # Kafka cluster or your Docker IP is different
    bootstrap-servers: localhost:9092
